apiVersion: batch/v1
kind: Job
metadata:
  name: "rds-db-{{ .Values.Job.ID}}"
spec:
  template:
    metadata:
      name: "rds-db-{{ .Values.Job.ID}}"
    spec:
      restartPolicy: "Never"
      imagePullPolicy: "Always"
      imagePullSecrets:
        - name: sohohouse-k8s-deploy-pull-secret
      containers:
      - name: "rds-db-{{ .Values.Job.ID}}"
        image: quay.io/sohohouse/postgres-rds:0.7
        command:
          - bash
          - "-c"
          - "/aws/bin/create-rds-in-vpc.sh"
        env:
        - name:  AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name:  AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name:  aws-credentials
              key:  AWS_SECRET_ACCESS_KEY
        - name:  AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name:  aws-credentials
              key:  AWS_REGION
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POSTGRES
          value: {{index .Values.Rds.Metadata "name" }}
        